---
Name: fromholdio-heroic
---
Page:
  extensions:
    - Fromholdio\Heroic\Extensions\HeroicPageExtension

---
Name: fromholdio-heroic-nomultisites
Except:
  moduleexists: 'symbiote/silverstripe-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Fromholdio\Heroic\Extensions\HeroicConfigExtension
