---
Name: fromholdio-heroic
---
Page:
  extensions:
    - Fromholdio\Heroic\Extensions\HeroicPageExtension

---
Name: fromholdio-heroic-nomultisites
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
    - 'fromholdio/silverstripe-configured-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Fromholdio\Heroic\Extensions\HeroicConfigExtension
